a-westerberg/WigellCarRental

src/main/java/com/wigell/wigellcarrental/repositories/CarRepository.java, src/main/java/com/wigell/wigellcarrental/repositories/CustomerRepository.java, src/main/java/com/wigell/wigellcarrental/repositories/OrderRepository.java, src/main/java/com/wigell/wigellcarrental/services/CarService.java, src/main/java/com/wigell/wigellcarrental/services/CarServiceImpl.java, src/main/java/com/wigell/wigellcarrental/services/CustomerService.java, src/main/java/com/wigell/wigellcarrental/services/CustomerServiceImpl.java, src/main/java/com/wigell/wigellcarrental/services/OrderService.java, src/main/java/com/wigell/wigellcarrental/services/OrderServiceImpl.java
* Created empty classes for Repositories and Services 
* Order is error until Booking class is renamed
=> WIG-13/16-SA 

src/main/java/com/wigell/wigellcarrental/controllers/CustomerController.java, src/main/java/com/wigell/wigellcarrental/entities/Car.java, src/main/java/com/wigell/wigellcarrental/entities/Customer.java, src/main/java/com/wigell/wigellcarrental/entities/Order.java, src/main/java/com/wigell/wigellcarrental/enums/CarStatus.java
Enum and small fixes in Entities
=> WIG-7/11/12-AA

src/main/java/com/wigell/wigellcarrental/configs/WebSecurityConfig.java
Added UserDetails in WebSecurityConfig
=> WIG-80-SJ Done.

src/main/java/com/wigell/wigellcarrental/services/OrderServiceImpl.java
* Added loggning for failed attempts on the endpoints: /removeorders-beforedate/{date}, /updateorderstatus/{orderId}/{status}, /updateordercar/{orderId}/{carId}, /cancelorder/{orderId}
=> WIG-113-SA 

src/test/java/com/wigell/wigellcarrental/services/CustomerServiceImplUnitTest.java
* Created testing class CustomerServiceImplUnitTest
* Created testing for the getCustomerById() method
=> WIG-110-SA

src/main/java/com/wigell/wigellcarrental/services/CarServiceImpl.java, src/main/java/com/wigell/wigellcarrental/services/CustomerServiceImpl.java, src/main/java/com/wigell/wigellcarrental/services/OrderServiceImpl.java, src/main/java/com/wigell/wigellcarrental/services/utilities/LogMethods.java, src/main/java/com/wigell/wigellcarrental/services/utilities/MicroMethods.java
Logmethods och implementation av dem i endpoints jag kodat
=> WIG-68-AWS

src/main/java/com/wigell/wigellcarrental/repositories/CarRepository.java, src/main/java/com/wigell/wigellcarrental/services/CarServiceImpl.java
=> WIG-122-AA

src/test/java/com/wigell/wigellcarrental/services/CustomerServiceImplUnitTest.java
* Added unit testing for updateCustomer()
=> WIG-109-SA

src/test/java/com/wigell/wigellcarrental/services/CustomerServiceImplAndCustomerRepositoryAndOrderRepositoryIntegrationTest.java, src/test/java/com/wigell/wigellcarrental/services/CustomerServiceImplUnitTest.java
* Added integrationtest for CustomerServiceImpl
* Changed so it uses the constructor in Customer
=> WIG-111-SA

src/main/java/com/wigell/wigellcarrental/repositories/CustomerRepository.java, src/main/java/com/wigell/wigellcarrental/services/CustomerServiceImpl.java, src/main/java/com/wigell/wigellcarrental/services/OrderServiceImpl.java
* Restructured Service methods - removecustomer, addorder & updateinfo. 
* Implemented LogMethodes into Service Methods - removecustomer, addorder & updateinfo. 
* Added small method in CustomerServiceImpl to clone Customer in usage of updateinfo.
=> WIG-89-90-91-SJ

src/main/java/com/wigell/wigellcarrental/services/OrderServiceImpl.java
=> WIG-120-AWS

src/test/java/com/wigell/wigellcarrental/services/CustomerServiceImplAndCustomerRepositoryAndOrderRepositoryIntegrationTest.java, src/test/java/com/wigell/wigellcarrental/services/CustomerServiceImplUnitTest.java
* Changed and imporved some things in unit test and integration
* Added variable for Principal
* Created integration test for updateCustomer()
=> WIG-112-SA

src/main/java/com/wigell/wigellcarrental/controllers/AdminController.java, src/main/java/com/wigell/wigellcarrental/services/CarServiceImpl.java
small fixes on deleteCar logging nd HttpStatus on addCar
=> WIG-125-AA

src/main/java/com/wigell/wigellcarrental/services/OrderServiceImpl.java
* Added the new LogMethods on the methods: updateOrderCar(), UpdateOrderStatus(), removeOrdersBeforeDate(), cancelOrder()
=> WIG-115-SA

src/test/java/com/wigell/wigellcarrental/services/CarServiceImplTest.java
Added testing for CarServiceImpl.getAvailableCars()
=> WIG-101-SJ

src/test/java/com/wigell/wigellcarrental/services/CustomerServiceImplAndCustomerRepositoryAndOrderRepositoryIntegrationTest.java, src/test/java/com/wigell/wigellcarrental/services/CustomerServiceImplUnitTest.java
* Moved around in assertEquals() so the excepted is first
=> WIG-112-SA 

src/main/java/com/wigell/wigellcarrental/services/OrderServiceImpl.java
* Changed in how to log so it looks cleaner
* Changed in cancelOrder to it also catches if the orders startDate or endDate is today and can't be cancelled
=> WIG-127-SA

src/test/java/com/wigell/wigellcarrental/services/CarServiceImplTest.java
=> WIG-102-SJ

src/test/java/com/wigell/wigellcarrental/controllers/CustomerControllerAndOrderServiceAndOrderRepositoryAndCustomerRepositoryAndCarRepositoryIntegrationTest.java, src/test/java/com/wigell/wigellcarrental/controllers/CustomerControllerAndOrderServiceAndOrderRepositoryIntegrationTest.java, src/test/java/com/wigell/wigellcarrental/services/CustomerServiceImplAndCustomerRepositoryAndOrderRepositoryIntegrationTest.java, src/test/java/com/wigell/wigellcarrental/services/OrderServiceImplUnitTest.java
Fixed my tests after updated cancelOrder() was updated.
=> WIG-124-AA

src/test/java/com/wigell/wigellcarrental/controllers/AdminCarFlowIntegrationTest.java, src/test/java/com/wigell/wigellcarrental/controllers/AdminControllerAndCarServiceAndCarRepositoryIntegrationTest.java, src/test/java/com/wigell/wigellcarrental/controllers/CustomerOrderFlowIntegrationTest.java, src/test/java/com/wigell/wigellcarrental/services/CarServiceImplTest.java
* Reworked class names for integration tests for readability.
=> WIG-105-SJ

src/main/java/com/wigell/wigellcarrental/services/CarServiceImpl.java, src/main/java/com/wigell/wigellcarrental/services/OrderServiceImpl.java
* Added for cancelOrder() and updateOrderCar() so if it's already happened it ends the action
* Added in incomeCar() to also get order that have startDate today
=> WIG-129-SA

src/main/java/com/wigell/wigellcarrental/models/entities/Car.java, src/main/java/com/wigell/wigellcarrental/services/OrderServiceImpl.java, src/main/resources/data.sql, src/test/java/com/wigell/wigellcarrental/controllers/AdminCarFlowIntegrationTest.java
* Added implementation into add order flow for new attribute "isCancelled". 
Smaller changes: 
Car regNo. was set to length 7, changed to 6 and changed Data.SQL to follow length.
=> WIG-132-SJ

src/main/java/com/wigell/wigellcarrental/configs/WebSecurityConfig.java, src/main/java/com/wigell/wigellcarrental/controllers/AdminController.java, src/main/java/com/wigell/wigellcarrental/controllers/CustomerController.java, src/main/java/com/wigell/wigellcarrental/models/entities/Car.java, src/main/java/com/wigell/wigellcarrental/models/entities/Customer.java, src/main/java/com/wigell/wigellcarrental/models/entities/Order.java, src/main/java/com/wigell/wigellcarrental/models/valueobjects/IncomeCar.java, src/main/java/com/wigell/wigellcarrental/repositories/OrderRepository.java, src/main/java/com/wigell/wigellcarrental/services/CarService.java, src/main/java/com/wigell/wigellcarrental/services/CustomerService.java, src/main/java/com/wigell/wigellcarrental/services/OrderService.java, src/main/java/com/wigell/wigellcarrental/services/OrderServiceImpl.java, src/main/resources/data.sql, src/test/java/com/wigell/wigellcarrental/services/CustomerServiceImplAndCustomerRepositoryAndOrderRepositoryIntegrationTest.java, src/test/java/com/wigell/wigellcarrental/services/CustomerServiceImplUnitTest.java
* Cleaned up my code
* Added my name on all the things I've done
=> WIG-130-SA
